package com.teenteen.teencash.presentation.utills

enum class CategoryAdapterKeys{
    CATEGORY, PIGGY_BANK
}

enum class DebtorAdapterKeys{
    MOTHERFUCKER, BLOODSUCKER
}

enum class AddBottomSheetKeys{
    ADD_PIGGY_BANK, SPENT_CATEGORY, SAVED_PIGGY, SET_LIMIT, CURRENT_BALANCE, CREATE_MOTHERFUCKER,
    CREATE_BLOODSUCKER, UPDATE_MOTHERFUCKER, UPDATE_BLOODSUCKER, UPDATE_CATEGORY, UPDATE_PIGGY,
    UPDATE_BALANCE
}

enum class ListBottomSheetKeys{
    CATEGORY_SETTINGS, PIGGY_BANK_SETTINGS, CHANGE_LANGUAGE, CHANGE_CURRENCY
}